apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yzk5n0p7p-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:d9bab3b453d2dd6567a1b5a06fd8036cd9e1f2fe@sha256:ba87195c14ebd8bb0e2a7eaf57c7624a5f7f080658e0818524127790cecab9cb
          name: container-image
