apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yzk5n0p7p-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/yzk5n0p7p-java-springboot-gitops